task: waymo_exp
source_path: /media/ml4u/ExtremeSSD/datasets/waymo/processed/181
exp_name: waymo_val_181

data:
  split_train: -1
  split_test: 4
  type: Waymo
  white_background: true
  selected_frames: [0, 160]
  cameras: [0]
  use_tracker: true
  extent: 20
  use_colmap: true
  mask_lidar_dynamic_object: false

model:
  gaussian:
    sh_degree: 1
    fourier_dim: 5
    fourier_scale: 1.
  nsg:
    include_bkgd: true
    include_obj: false
    include_sky: false
    opt_track: true
    use_deformation_model: false
  deformable:
    net_width: 64
    timebase_pe: 4
    defor_depth: 1
    posebase_pe: 10
    scale_rotation_pe: 2
    opacity_pe: 2
    timenet_width: 64
    timenet_output: 32
    bounds: 1.6
    plane_tv_weight: 0.0001
    time_smoothness_weight: 0.01
    l1_time_planes: 0.0001
    multires: [1, 2, 4, 8]
    no_dx: False
    no_grid: False
    no_ds: True 
    no_dr: True
    no_do: True
    no_dshs: False
    feat_head: True
    empty_voxel: False
    grid_pe: 0
    static_mlp: False
    apply_rotation: False
  kplanes_config: 
    grid_dimensions: 2
    input_coordinate_dim: 4
    output_coordinate_dim: 32
    resolution: [64, 64, 64, 25]

train:
  iterations: 30000
  test_iterations: [7000, 29999]
  checkpoint_iterations: [30000]

optim:
  prune_box_interval: 100
  densification_interval: 100
  densify_from_iter: 500
  densify_grad_threshold: 0.0002
  densify_until_iter: 15000
  feature_lr: 0.0025
  max_screen_size: 20
  min_opacity: 0.005
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  percent_big_ws: 0.1
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 1.6e-06
  position_lr_init: 0.00016
  position_lr_max_steps: 30000
  rotation_lr: 0.001
  scaling_lr: 0.005
  semantic_lr: 0.01

  lambda_dssim: 0.2
  lambda_mask: 0.1
  lambda_reg: 0.1
  lambda_depth_lidar: 0.01
  lambda_l1: 3.

  track_position_lr_delay_mult: 0.01
  track_position_lr_init: 0.005
  track_position_lr_final: 5.0e-5
  track_position_max_steps: 30000

  track_rotation_lr_delay_mult: 0.01
  track_rotation_lr_init: 0.001
  track_rotation_lr_final: 1.0e-5
  track_rotation_max_steps: 30000

render:
  fps: 30